name: Content quality checks

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  check-content:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt || true; fi

      - name: Run content-quality checks
        run: |
          python scripts/ci_content_quality.py
