name: Link Check
on:
  push:
  pull_request:
permissions:
  contents: read
jobs:
  lychee:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: lycheeverse/lychee-action@v1
        with:
          args: --verbose --no-progress --include-fragments --accept 200,206,429 .
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}