# This workflow validates HTML, CSS, and JavaScript for the static website
# Designed for static sites that may not have traditional Node.js build processes

name: Static Site Validation

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  validate:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v4
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    
    - name: Check if package.json exists
      id: check-package
      run: |
        if [ -f "package.json" ]; then
          echo "package-exists=true" >> $GITHUB_OUTPUT
        else
          echo "package-exists=false" >> $GITHUB_OUTPUT
        fi
    
    - name: Create package-lock.json if missing
      if: steps.check-package.outputs.package-exists == 'true'
      run: |
        if [ ! -f "package-lock.json" ]; then
          echo "Creating package-lock.json..."
          npm install --package-lock-only || echo "Package-lock generation failed, will try npm install"
        fi
    
    - name: Install dependencies
      if: steps.check-package.outputs.package-exists == 'true'
      run: |
        if [ -f "package-lock.json" ]; then
          npm ci
        else
          npm install
        fi
    
    - name: Run build script (if present)
      if: steps.check-package.outputs.package-exists == 'true'
      run: |
        if npm run build --if-present; then
          echo "Build completed successfully"
        else
          echo "Build script not found or failed - continuing as this is a static site"
        fi
    
    - name: Run tests (if present)
      if: steps.check-package.outputs.package-exists == 'true'
      run: |
        if npm test; then
          echo "Tests completed successfully"
        else
          echo "Tests failed or not found - continuing as this may be a static site"
        fi
    
    - name: Basic file structure validation
      run: |
        echo "Validating basic file structure..."
        
        # Check for essential files
        if [ -f "index.html" ]; then
          echo "✓ index.html found"
        else
          echo "✗ index.html not found"
          exit 1
        fi
        
        # Check for assets directory
        if [ -d "assets" ]; then
          echo "✓ assets directory found"
        else
          echo "⚠ assets directory not found"
        fi
        
        # Check for basic HTML syntax in main files
        for file in *.html; do
          if [ -f "$file" ]; then
            if grep -q "DOCTYPE" "$file" && grep -q "<html" "$file"; then
              echo "✓ $file has basic HTML structure"
            else
              echo "⚠ $file may have HTML structure issues"
            fi
          fi
        done
        
        echo "File structure validation completed"
